In [2]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [20]:
'''
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
'''

'\nQ1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code\nto print the data types of both the variables.\n'

In [21]:
'''
where the data type of list are list and there element data type are str
in array_list that data type are numpy.ndarray means array and there element data type are str.
'''

'\nwhere the data type of list are list and there element data type are str\nin array_list that data type are numpy.ndarray means array and there element data type are str.\n'

In [22]:
print(type(list_))

<class 'list'>


In [23]:
print(type(array_list))

<class 'numpy.ndarray'>


In [24]:
print(type(list_[0]))

<class 'str'>


In [25]:
print(type(array_list[0]))

<class 'numpy.str_'>


In [26]:
'''
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
'''

'\nQ2. Write a code to print the data type of each and every element of both the variables list_ and\narra_list.\n'

In [35]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)
for i in range(len(list_)):
    print('list: ',type(i))
for i in range(len( array_list)):
    print("array_list :",type(array_list[i]))

list:  <class 'int'>
list:  <class 'int'>
list:  <class 'int'>
list:  <class 'int'>
list:  <class 'int'>
array_list : <class 'numpy.str_'>
array_list : <class 'numpy.str_'>
array_list : <class 'numpy.str_'>
array_list : <class 'numpy.str_'>
array_list : <class 'numpy.str_'>


In [36]:
'''
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
'''

'\nQ3. Considering the following changes in the variable, array_list:\narray_list = np.array(object = list_, dtype = int)\nWill there be any difference in the data type of the elements present in both the variables, list_ and\narra_list? If so then print the data types of each and every element present in both the variables, list_\nand arra_list.\nConsider the below code to answer further questions:\nimport numpy as np\nnum_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]\nnum_array = np.array(object = num_list)\n'

In [37]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list,dtype=int)

In [47]:
type(num_list)

list

In [46]:
type(num_array)

numpy.ndarray

In [58]:
len(num_array[0])

3

In [60]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list,dtype=int)
for i in range(len(num_list)):
    for j in range(len(num_list[i])):
        print("num_list element type : ",type(num_list[i][j]))
for i in range(len(num_array)):
    for j in range(len(num_array[i])):
        print("num_array element : ",type(num_array[i][j]))
                

num_list element type :  <class 'int'>
num_list element type :  <class 'int'>
num_list element type :  <class 'int'>
num_list element type :  <class 'int'>
num_list element type :  <class 'int'>
num_list element type :  <class 'int'>
num_array element :  <class 'numpy.int64'>
num_array element :  <class 'numpy.int64'>
num_array element :  <class 'numpy.int64'>
num_array element :  <class 'numpy.int64'>
num_array element :  <class 'numpy.int64'>
num_array element :  <class 'numpy.int64'>


In [61]:
'''
where the data type of num list are list and num array type are array . and the data type 
of both element are int see you in code 
'''

'\nwhere the data type of num list are list and num array type are array . and the data type \nof both element are int see you in code \n'

In [62]:
'''
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
'''

'\nQ4. Write a code to find the following characteristics of variable, num_array:\n(i) shape\n(ii) size\n'

In [63]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
num_array.size

6

In [65]:
num_array.shape

(2, 3)

In [66]:
'''
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
'''

'\nQ5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array\ncreation function.\n[Hint: The size of the array will be 9 and the shape will be (3,3).]\n'

In [67]:
import numpy as np


In [68]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
arr = np.random.randint(0,1, (3,3))

In [80]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [81]:
'''
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
'''

'\nQ6. Create an identity matrix of shape (5,5) using numpy functions?\n[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]\n'

In [90]:
import numpy.matlib as nm

In [92]:
arr=nm.eye((5))

In [93]:
arr

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [94]:
a=nm.identity(5)

In [95]:
a

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])